//
// Created by 20174019 on 24/05/2021.
//

#ifndef UNIFIED_MAKEFILE_PROJECT1_RAILCONSTRAINT_H
#define UNIFIED_MAKEFILE_PROJECT1_RAILCONSTRAINT_H


class RailConstraint {

};


#endif //UNIFIED_MAKEFILE_PROJECT1_RAILCONSTRAINT_H
